import './globals.css'
import type { Metadata } from 'next'
import { Noto_Sans_Javanese } from 'next/font/google'

const NotoSansJavanese = Noto_Sans_Javanese({
  weight: ["600"],
  display: 'swap',
  preload: false,
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={NotoSansJavanese.className}>{children}</body>
    </html>
  )
}
